# Generated by Django 3.0.5 on 2020-05-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contry_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='photo')),
            ],
        ),
    ]
