# Generated by Django 3.0.5 on 2020-05-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contry',
            name='img10',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='img2',
            field=models.ImageField(default=' ', upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='img3',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='img4',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='img5',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='img6',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='img7',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='img8',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='img9',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
    ]
