# Generated by Django 3.0.5 on 2020-05-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvapp', '0002_auto_20200511_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='contry',
            name='historyt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
