# Generated by Django 3.0.5 on 2020-05-11 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trvapp', '0003_contry_historyt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contry',
            old_name='historyt',
            new_name='history',
        ),
    ]
