# Generated by Django 3.0.5 on 2020-05-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvapp', '0005_auto_20200512_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='contry',
            name='geography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contry',
            name='wather',
            field=models.TextField(blank=True, null=True),
        ),
    ]
