# Generated by Django 3.0.5 on 2020-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvapp', '0006_auto_20200512_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='contry',
            name='tag1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='tag2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='tag3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='tag4',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='tag5',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='tag6',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
