# Generated by Django 3.0.8 on 2020-08-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvapp', '0009_auto_20200610_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='contry',
            name='img22',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='img33',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='img44',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='img55',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='img777',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contry',
            name='img96',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
    ]
