# Generated by Django 3.0.8 on 2020-08-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvapp', '0010_auto_20200812_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='contry',
            name='tag11',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contry',
            name='tag22',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contry',
            name='tag33',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contry',
            name='tag44',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contry',
            name='tag55',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contry',
            name='tag66',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
