# Generated by Django 3.0.8 on 2020-08-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trvapp', '0011_auto_20200812_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contry',
            old_name='img777',
            new_name='img66',
        ),
        migrations.RenameField(
            model_name='contry',
            old_name='img96',
            new_name='img77',
        ),
    ]
