# Generated by Django 3.0.5 on 2020-05-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavelfeatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuers',
            name='tilte2',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte3',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte4',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte5',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte6',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte7',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
