# Generated by Django 3.0.5 on 2020-05-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavelfeatures', '0002_auto_20200525_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuers',
            name='tilte',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='featuers',
            name='tilte2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='featuers',
            name='tilte3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='featuers',
            name='tilte4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='featuers',
            name='tilte5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='featuers',
            name='tilte6',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='featuers',
            name='tilte7',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
