# Generated by Django 3.0.5 on 2020-06-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavelfeatures', '0003_auto_20200525_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuers',
            name='contant10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='contant11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='contant12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='contant13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='contant14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='contant15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='contant16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='contant7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='contant8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='contant9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte10',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte11',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte12',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte13',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte14',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte15',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte16',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte17',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte8',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte9',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
