# Generated by Django 3.0.5 on 2020-06-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavelfeatures', '0004_auto_20200611_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuers',
            name='tilte1_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte2_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte3_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte4_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte5_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte6_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte7_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte8_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuers',
            name='tilte9_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
