# Generated by Django 3.0.5 on 2020-06-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavelfeatures', '0005_auto_20200611_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuers',
            name='img6',
            field=models.ImageField(default='', upload_to='pictuer2'),
            preserve_default=False,
        ),
    ]
