# Generated by Django 3.0.5 on 2020-06-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavelfeatures', '0006_featuers_img6'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuers',
            name='img7',
            field=models.ImageField(default='', upload_to='pictuer2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuers',
            name='img8',
            field=models.ImageField(default='', upload_to='pictuer2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuers',
            name='img9',
            field=models.ImageField(default='', upload_to='pictuer2'),
            preserve_default=False,
        ),
    ]
