# Generated by Django 3.0.5 on 2020-06-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavelfeatures', '0007_auto_20200611_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuers',
            name='img10',
            field=models.ImageField(default='', upload_to='pictuer2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuers',
            name='img11',
            field=models.ImageField(default='', upload_to='pictuer2'),
            preserve_default=False,
        ),
    ]
