# Generated by Django 3.0.5 on 2020-06-16 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodanddrink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(blank=True, max_length=500, null=True)),
                ('tilte2', models.CharField(blank=True, max_length=500, null=True)),
                ('tilte3', models.CharField(blank=True, max_length=500, null=True)),
                ('tilte4', models.CharField(blank=True, max_length=500, null=True)),
                ('tilte5', models.CharField(blank=True, max_length=500, null=True)),
                ('tilte6', models.CharField(blank=True, max_length=500, null=True)),
                ('tilte7', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('contant1', models.TextField(blank=True, null=True)),
                ('contant2', models.TextField(blank=True, null=True)),
                ('contant3', models.TextField(blank=True, null=True)),
                ('contant5', models.TextField(blank=True, null=True)),
                ('contant6', models.TextField(blank=True, null=True)),
                ('create', models.DateTimeField(default=datetime.datetime.now)),
                ('img1', models.ImageField(upload_to='pictuer2')),
                ('img2', models.ImageField(upload_to='pictuer2')),
                ('img3', models.ImageField(upload_to='pictuer2')),
                ('img4', models.ImageField(upload_to='pictuer2')),
                ('img5', models.ImageField(upload_to='pictuer2')),
            ],
        ),
        migrations.RenameModel(
            old_name='FoodAndDrink',
            new_name='Drink',
        ),
    ]
