# Generated by Django 3.0.5 on 2020-06-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodanddrink', '0003_auto_20200617_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='contant10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='contant11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='contant12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='contant13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='contant14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='contant15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='contant16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='contant17',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='contant7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='contant8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='contant9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='img10',
            field=models.ImageField(default='', upload_to='pictuer2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='img11',
            field=models.ImageField(default='', upload_to='pictuer2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='img12',
            field=models.ImageField(default='', upload_to='pictuer2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='img6',
            field=models.ImageField(default='', upload_to='pictuer2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='img7',
            field=models.ImageField(default='', upload_to='pictuer2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='img8',
            field=models.ImageField(default='', upload_to='pictuer2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='img9',
            field=models.ImageField(default='', upload_to='pictuer2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte10',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte10_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte11',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte11_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte12',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte12_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte13',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte14',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte15',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte16',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte17',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte18',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte19',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte1_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte20',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte21',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte22',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte2_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte3_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte4_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte5_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte6_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte7_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte8',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte8_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte9',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='tilte9_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
