# Generated by Django 3.0.5 on 2020-06-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodanddrink', '0004_auto_20200618_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
