# Generated by Django 3.0.5 on 2020-06-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodanddrink', '0005_auto_20200620_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
